#!/bin/bash
if [ $# -lt 1 ] ;then
    maven.bat
    echo -e "\e[32m  maven list -r:http://repo1.maven.org/maven2/ -m:groupId:artifactId\e[0m"
    exit 0
fi
redirect=true
opts=
repository=http://repo1.maven.org/maven2/
groupId=
artifactId=
version=
cmd=
for o in $*
do
    case $o in
        list)
            cmd=list
            redirect=
            ;;
        -r:*)
            repository=${o#-r:}
            ;;
        -m:*)
            if [ "${o//\//.}" != "$o" ] ;then
                coo=${o#*:}
                coo=${coo#/}
                coo=${coo%/}
                version=${coo##*/}
                coo=${coo%/*}
                artifactId=${coo##*/}
                coo=${coo%/*}
                groupId=${coo//\//.}
                opts+=" -m:$groupId:$artifactId:jar:$version"
            else
                opts+=" $o"
                coo=${o#-m:}
                groupId=${coo%%:*}
                artifactId=${coo##*:}
            fi
            ;;
        *)
            opts+=" $o"
            ;;
    esac
done

if [ -n "$redirect" ] ;then
    maven.bat $opts
else
    valid=
    while read ln ;do
        line=$(echo $ln|tr -d [:blank:])
        if [ "$line" == "</repository>" ];then
            valid=
        fi
        if [ -n "$valid" ] ;then
            len=$(expr length "$line")
            if [ $(expr match "$line" "^<url>[^<>]*</url>$") -eq $len ] ;then
                rep=${line#*>}
                rep=${rep%<*}
                echo $repository|grep -q $rep>/dev/null 2>&1
                [ $? -eq 1 ] && repository="$rep $repository"
            fi
        fi
        if [ "$line" == "<repository>" ] ;then
            valid=true
        fi
    done<~/.m2/settings.xml
    echo -e "\e[31mrepos: $repository\e[0m"
    case $cmd in
        list)
            for rep in $repository ;do
                list=$(curl "${rep%/}/${groupId//./\/}/${artifactId}/" -qs|while read ln ;do
                        echo $ln|grep -q ".*<a href=[^<>]*>[^<>/]*/</a>.*"
                        if [ $? -eq 0 ] ;then
                            release=${ln%%/</a>*}
                            release=${release##*>}
                            if [ -n "$release" ] ;then
                                if [ -z "$first" ] ;then
                                    first=true
                                    echo $release
                                else
                                    echo " $release"
                                fi
                            fi
                        fi
                    done)
                if [ -n "$list" ] ;then
                    echo -e "\e[32m $list \e[0m"
                    exit 0
                fi
            done
            ;;
        *)
            ;;
    esac
fi