#!/bin/bash
if [ $# -lt 1 ] ;then
    maven.bat
    echo -e "\e[32m  maven list -r:http://repo1.maven.org/maven2/ -m:groupId:artifactId\e[0m"
    exit 0
fi
redirect=true
opts=
repository=http://repo1.maven.org/maven2/
groupId=
artifactId=
version=
cmd=
for o in $*
do
    case $o in
        list)
            cmd=list
            redirect=
            ;;
        -r:*)
            repository=${o#-r:}
            ;;
        -m:*)
            if [ "${o//\//.}" != "$o" ] ;then
                coo=${o#*:}
                coo=${coo#/}
                coo=${coo%/}
                version=${coo##*/}
                coo=${coo%/*}
                artifactId=${coo##*/}
                coo=${coo%/*}
                groupId=${coo//\//.}
                opts+=" -m:$groupId:$artifactId:jar:$version"
            else
                opts+=" $o"
                coo=${o#-m:}
                groupId=${coo%%:*}
                artifactId=${coo##*:}
            fi
            ;;
        *)
            opts+=" $o"
            ;;
    esac
done

if [ -n "$redirect" ] ;then
    maven.bat $opts
else
    case $cmd in
        list)
            curl "${repository%/}/${groupId//./\/}/${artifactId}/" -qs|grep "^<a href=[^<>]*>[^<>/]*/</a>.*$"|awk -F\> '{print $2}'|awk -F/ '{print $1}'
            ;;
        *)
            ;;
    esac
fi