#!/bin/bash
gav="${1}"
for f in $(find ${2:-.} -type f) ;do
	matches=$(grep -ns "^   $gav" $f)
	if [ $? -ne 0 ] ;then continue ;fi
	matches=$(echo "$matches"|awk -F: '{print $1}')
	echo ${f#*/}
	for match in $matches ;do
		cur=$match
		while [ $cur -gt 0 ] ;do
			text=$(sed "${cur}q;d" $f)
			expr match "$text" "^[^ ]">/dev/null 2>&1
			[ $? -eq 0 ] && echo "  $text" && break
			let "cur-=1"
		done
	done
done
