#!/usr/bin/env bash
set -e

command_name=${0%.*}
command_name=${command_name##*/}

jar_ip="${BASH_SOURCE%/*}/soiffip.jar"
jar_port="${BASH_SOURCE%/*}/soiffport.jar"

function usage() {
      red "Usage:"
    green "  $command_name {config [options]|debug [options]|run [options]|stop|logs [options]|ps|exec <arguments>}|upgrade"
      red "Options:"
      red "  config: add additional options for edas-config-center"
    green "    <docker-run-options>                  #additional options comes from \`docker run --help\`"
      red "  debug|run: start container for current module"
    green "    --auto                                #assign local ip address to \`--reg\` and \`--hsf-host\`"
    green "                                          #and assign random port to \`--hsf-port\` if it's not specified"
    green "    --reg=<registry-ip-address>           #edas configuration server address"
    green "    --cfg=<spring-cloud-config-server>    #spring cloud config server address"
    green "    --hsf-port=<hsf.server.port>          #port for hsf server"
    green "    --hsf-http-port=<hsf.http.port>       #port for hsf http protocol"
    green "    --hsf-host=<hsf.server.ip>            #ip address for hsf publisher"
    green "    <docker-run-options>                  #additional options comes from \`docker run --help\`"
      red "  debug: start container with java debugger enabled for current module"
    green "    --dbg=<debug-port>                    #java remote debugger port"
      red "  logs: display logging greenrmation for current container"
    green "    <docker-logs-options>                 #additional options comes from \`docker logs --help\`"
      red "  exec: execute command in current container in interactive mode"
    green "    <arguments>                           #additional arguments for \`docker exec\`"
      red "Description:"
    green "  To deploy EDAS application into docker container on localhost, which means docker is pre-required."
    green "  Docker container named by current folder name with prefix of \`edas-\`"
      red "Examples:"
      red "  # start edas config center"
    green "  [root@app1 ~]# $command_name config"
      red "  # start docker container for current maven module and the config center host is \`10.80.1.23\`"
    green "  [root@app1 ~]# $command_name debug --reg=10.80.1.23 --dbg=5005 -e local_db_host=10.80.1.23"
    green "  [root@app1 ~]# $command_name run --reg=10.80.1.23 -e local_db_host=10.80.1.23"
      red "  # stop docker container for current maven module"
    green "  [root@app1 ~]# $command_name stop"
}

function red() {
    echo -e "\033[31m$*\033[0m"
}

function green() {
    echo -e "\033[32m$*\033[0m"
}

function fatal() {
    red $*
    usage
}

function stop() {
    green "Trying to stop container $1 ...";
    count=`docker ps -f name=$1|wc -l`;
    [ $count -eq 2 ] && docker stop $1;
    green "Trying to remove container $1 ..."
    count=`docker ps -af name=$1|wc -l`;
    [ $count -eq 2 ] && docker rm $1;
    return 0
}

function preview() {
    options=${options# }
    jvmoptions=${jvmoptions# }
    green "You are going to execute : "
      red "   action : $cmd"
      red "  options : $options"
      red "      jvm : $jvmoptions"
}

function upgrade() {
    for e in $* ;do
        case $e in
            $jar_ip)
                curl -skSL http://git.oschina.net/soiff/soiff-ip/raw/master/releases/soiffip.jar -o $e
                return $?
                ;;
            $jar_port)
                curl -skSL http://git.oschina.net/soiff/soiffport/raw/master/releases/soiffport.jar -o $e
                return $?
                ;;
            $BASH_SOURCE)
                curl -skSL http://git.oschina.net/soiff/script/raw/master/bash/hsf -o $e && chmod +x $e
                return $?
                ;;
        esac
    done
}

function check() {
    components=( "$jar_ip $jar_port" )
    for c in $components ;do
        if [ ! -e "${c}" ] ;then
            upgrade "$c"
        fi
    done
}

check

cmd=

registry_ip=
config_ip=
options=""
jvmoptions=""
for c in $* ;do
    case $c in
        --auto)
            using_default=true
            ;;
        --reg=*)
            registry_ip=${c#*=}
            ;;
        --cfg=*)
            config_ip=${c#*=}
            ;;
        --hsf-port=*)
            v=${c#*=}
            hsf_port=$v
            ;;
        --hsf-http-port=*)
            v=${c#*=}
            options+=" -p $v:$v"
            jvmoptions+=" -Dhsf.http.port=$v"
            ;;
        --hsf-host=*)
            v=${c#*=}
            hsf_host=$v
            ;;
        config|logs|stop|ps|exec|run)
            cmd=$c
            ;;
        debug)
            cmd=$c
            jvmoptions+=" -Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:5005,suspend=n,server=y"
            ;;
        --dbg=*)
            v=${c#*=}
            debug_port=$v
            ;;
        upgrade)
            upgrade "$jar_ip"
            upgrade "$jar_port"
            upgrade "${BASH_SOURCE}"
            exit $?
            ;;
        *)
            options+=" ${c// /\\ }"
            ;;
    esac
done

if [ "${using_default:-false}" == "true" ] ;then
    hsf_host=`java -jar $jar_ip|grep "sitelocal,ipv4"|awk -F, '{print $3}'`
    if [ -z "$hsf_port" ] ;then
        hsf_port=`java -jar $jar_port`
    fi
    if [ -z "$debug_port" ] ;then
        debug_port=`java -jar $jar_port`
    fi
    if [ -z "$registry_ip" ] ;then
        registry_ip=$hsf_host
    fi
fi

if [ -n "$hsf_host" ] ;then
    jvmoptions+=" -DHsfBindHost=0.0.0.0 -Dhsf.server.ip=$hsf_host"
fi

if [ -n "$hsf_port" ] ;then
    options+=" -p $hsf_port:$hsf_port"
    jvmoptions+=" -Dhsf.server.port=$hsf_port"
fi

container=edas-${PWD##*/};

case $cmd in
    stop)
        preview
        stop $container
        ;;
    logs)
        preview
        docker logs $options $container
        ;;
    config)
        container_config=edas-config-center
        stop $container_config
        preview
        docker run --name=$container_config -d -p 8080:8080 -p 9600:9600 $options \
            index.tenxcloud.com/revolc/edas-config-center:latest
        ;;
    ps)
        preview
        docker ps -af name=$container
        ;;
    exec)
        preview
        docker exec -it $container ${options:-bash}
        ;;
    debug|run)
        options+=" --add-host=jmenv.tbsite.net:${registry_ip:-192.168.103.108} --add-host=config.tesir.top:${config_ip:-192.168.103.101}"
        stop $container
        if [ ! -e target -o ! -d target ] ;then
            fatal "Target is not exist or is not a folder."
            exit -1
        fi

        finalName=`mvn help:evaluate -Dexpression=project.build.finalName 2>/dev/null|grep -v "^\[green\].*$"|grep -v "^.*\s.*$"`

        [ $? -ne 0 ] && {
            fatal "Cannot retrieve the final name for this artifact."
            exit -1
        }

        [ ! -e target/$finalName.war ] && {
            fatal "Not a valid hsf application."
            exit -1
        }

        [ ! -e target/deploy ] && mkdir target/deploy;
        [ ! -e target/deploy/$finalName.war ] && cp target/$finalName.war target/deploy/$finalName.war;

        #/d/source/directory
        local_wd=$PWD/target/deploy;
        if [ -n "${USERPROFILE}" ] ;then
            #bash from windows
            local_wd=${local_wd//\//\\};
            local_wd=${local_wd#\\};
            local_wd=${local_wd/\\/:\\};
        fi

        green "Mounting ${local_wd//\\/\\\\} ...";
        image=
        case $cmd in
            debug)
                image=index.tenxcloud.com/revolc/edas:latest
                if [ -n "$debug_port" ] ;then
                    options+=" -p $debug_port:5005"
                else
                    options+=" -p 5005:5005"
                fi
                ;;
            run)
                image=index.tenxcloud.com/revolc/edas-production:latest
                ;;
            *)
                fatal "Unexpected command $cmd"
                exit -1
                ;;
        esac
        
        preview
        if [ -n "$jvmoptions" ] ;then
            docker run --name=$container -d -v $local_wd:/opt/taobao-tomcat-7.0.59/deploy \
                ${options:+${options}} -e JAVA_OPTS="${jvmoptions}" $image
        else
            docker run --name=$container -d -v $local_wd:/opt/taobao-tomcat-7.0.59/deploy \
                ${options:+${options}} $image
        fi
        ;;
    *)
        usage
        ;;
esac
