#!/usr/bin/env bash

const_m=${BASH_SOURCE}

if [ "${const_m:0:8}" == "/dev/fd/" ] ;then
    # from pipe
    const_m=
fi

const_source_dir=${const_m%/*}
const_command=${const_m##*/}

const_url_m="https://git.oschina.net/soiff/scripts/raw/master/bash/m"
const_version="1.0.4"

opt_goals=
opt_options="-Dmaven.test.skip -Dmaven.javadoc.skip"

function red() {
    echo -e "\033[31m$*\033[0m"
}

function green() {
    echo -e "\033[32m$*\033[0m"
}

function usage() {
      red "Usage: ${const_command} {c|va|co|t|p|v|i|s|d|help|upgrade}"
    green "  c            : clean"
    green "  va           : validate"
    green "  co           : compile"
    green "  t            : test"
    green "  p            : package"
    green "  v            : verify"
    green "  i            : install"
    green "  s            : site"
    green "  d            : deploy"
    green "  help         : same as --help"
    green "  upgrade      : upgrade to latest release"
      red "Supported options:"
    green "  --help       : show help"
    green "  -v|--version : show version information"
    green "  -*           : additional options"
    green "  *            : additional goals"
}

function release() {
      red "v${const_version}"
    green "  1. Update upgrade management;"
      red "v1.0.3"
    green "  1. Support additional goals, such as 'help:evaluate';"
    green "  2. Add release log support;"
}

for c in $* ;do
    case ${c} in
        c)
            # clean
            opt_goals+=" clean"
            ;;
        va)
            # validate
            opt_goals+=" validate"
            ;;
        co)
            # compile
            opt_goals+=" compile"
            ;;
        t)
            # test
            opt_goals+=" test"
            ;;
        p)
            # package
            opt_goals+=" package"
            ;;
        v)
            # verify
            opt_goals+=" verify"
            ;;
        i)
            # install
            opt_goals+=" install"
            ;;
        s)
            # site
            opt_goals+=" site"
            ;;
        d)
            # deploy
            opt_goals+=" deploy"
            ;;
        upgrade)
            if [ -n "${const_m}" -a -e "${const_m}" ] ;then
                curl -skSL "${const_url_m}" -o "${const_m}"
                if [ $? -eq 0 ] ;then
                    chmod +x "${const_m}"
                fi
                green "Congratulations, 'm' has been upgraded to latest version ${const_version}!"
                ${const_m} release
                exit $?
            fi
            red "'m' has not been installed, please install it by \`bash <(curl -skSL ${const_url_m})\`!"
            exit 0
            ;;
        release)
            release
            exit 0
            ;;
        -h|--help|help)
            usage
            exit 0
            ;;
        -v|--version)
            red "${const_version}"
            exit 0
            ;;
        -*)
            opt_options+=" ${c}"
            ;;
        *)
            # treat as additional goals
            opt_goals+=" ${c}"
            ;;
    esac
done

if [ $# -eq 0 ] ;then
    if [ -z "${const_m}" -o ! -e "${const_m}" ] ;then
        for d in ${PATH//:/ } ;do
            v_dir="$d"
            v_m="${v_dir}/m"
            if [ -e ${v_dir} ] ;then
                if [ ! -e ${v_m} ] ;then
                    curl -skSL "${const_url_m}" -o "${v_m}">/dev/null 2>&1
                    if [ $? -ne 0 ] ;then
                        continue
                    fi
                    chmod +x ${v_m}>/dev/null 2>&1
                    if [ $? -ne 0 ] ;then
                        continue
                    fi
                    green "Congratulations, 'm' has been installed into ${v_dir}, enjoy yourself!"
                    break
                fi
            fi
        done
    else
        usage
    fi
else
    which mvn>/dev/null 2>&1
    if [ $? -eq 0 ] ;then
        v_cmd="mvn ${opt_goals# } ${opt_options}"
        green "${v_cmd}"
        ${v_cmd}
    else
        red "'mvn' has not been found in PATH, please make sure maven has been installed already."
    fi
fi
