#!/bin/bash

e_notfound="\e[31mno proper maven installation found.\e[0m"

grep -q "export M2_HOME=" ~/.bashrc

if [ -z "$M2_HOME" ] ;then
    source ~/.bashrc>/dev/null 2>&1
fi

isfirst=1
if [ -n "$M2_HOME" -a -e "$M2_HOME" ] ;then
    isfirst=0
else
    read -p "please specify maven installation path:" M2_HOME
fi
if [ -n "$M2_HOME" -a -e "$M2_HOME" ] ;then
    mvn="$M2_HOME/bin/mvn"
    [ ! -e "$mvn" ] && echo -e ${e_notfound} && exit -1;
    [ $isfirst -eq 1 ] && export M2_HOME && echo export M2_HOME=$M2_HOME>>~/.bashrc
    exec $mvn $*
else
    echo -e ${e_notfound} && exit -1;
fi
